---

- name: "Create subdirectories for archivematica-mcp-server source files"
  file:
    dest: "{{ item }}"
    state: "directory"
  with_items:
    - "/etc/archivematica"
    - "/usr/lib/archivematica"
    - "/usr/share/archivematica"
    - "/usr/share/dbconfig-common/data/archivematica-mcp-server/install/"
    - "/usr/share/dbconfig-common/data/archivematica-mcp-server/upgrade/mysql/"

- name: "Copy archivematica-mcp-server source files"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
  with_items:
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/etc"
      dest: "/etc/archivematica/MCPServer"
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/lib"
      dest: "/usr/lib/archivematica/MCPServer"
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/share"
      dest: "/usr/share/archivematica/MCPServer"
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/share/mysql"
      dest: "/usr/share/dbconfig-common/data/archivematica-mcp-server/install/mysql"
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/init/archivematica-mcp-server.conf"
      dest: "/etc/init/archivematica-mcp-server.conf"

- name: "Copy archivematica-mcp-server init service"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
  with_items:
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/init/archivematica-mcp-server.conf"
      dest: "/etc/init/archivematica-mcp-server.conf"

- name: "Reload Upstart configuration"
  command: "initctl reload-configuration"

- name: "Install archivematica-mcp-server package dependencies"
  apt:
    pkg: "{{ item }}"
    state: "latest"
  with_items:
    - "dbconfig-common"
    - "logapp"
    - "python-pyinotify"
    - "python-gearman"
    - "python-mysqldb"
    - "python-lxml"
    - "uuid"

# Note that when we are using mysql_db and mysql_user we are assuming that the
# root user has a local ~/.my.cnf configuration file with the credentials in it
# for the MySQL user.

- name: "Create MySQL database"
  mysql_db:
    name: "MCP"
    state: "present"
    encoding: "utf8"
    collation: "utf8_unicode_ci"
  register: "createdb_result"

- name: "Initialize database MCP"
  mysql_db:
    name: "MCP"
    state: "import"
    target: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/share/mysql"
  when: "createdb_result|changed"

- name: "Create MySQL user"
  mysql_user:
    name: "archivematica"
    password: "demo"
    priv: "MCP.*:ALL"
    state: "present"

- name: "Create archivemaitca-mcp-server log directories"
  file:
    dest: "{{ item }}"
    state: "directory"
    owner: "archivematica"
    group: "archivematica"
    mode: "g+s"
  with_items:
    - "/var/log/archivematica/MCPServer"

- name: "Create /var/archivematica/sharedDirectory"
  file:
    dest: "/var/archivematica/sharedDirectory"
    state: "directory"

# TODO: note that the location of sharedDirectory structure differs from the debian installer location

- name: "Create /var/archivematica/sharedDirectory structure"
  command: "rsync -a /usr/share/archivematica/MCPServer/sharedDirectoryStructure/ /var/archivematica/sharedDirectory/"

- name: "Set owner, group of /var/archivematica recursively"
  file:
    dest: "/var/archivematica"
    state: "directory"
    recurse: "yes"
    owner: "archivematica"
    group: "archivematica"

- name: "Set owner, group of /var/archivematica/sharedDirectory recursively"
  file:
    dest: "/var/archivematica/sharedDirectory"
    state: "directory"
    recurse: "yes"
    owner: "archivematica"
    group: "archivematica"

- name: "Set permissions for /var/archivematica"
  command: "chmod -R g+s /var/archivematica/"

- name: "Set permissions for /var/archivematica/sharedDirectory"
  command: "chmod -R 664 /var/archivematica/sharedDirectory"

- name: "Set more permissions for /var/archivematica"
  shell: "find -L /var/archivematica/ -type d  | sudo xargs -IF chmod u+rwx,g+rwxt,o-rwx F"

- name: "Enable services"
  service:
    name: "{{ item }}"
    state: "started"
    enabled: "yes"
  with_items:
    - "archivematica-mcp-server"