---

#
# Common tasks
#


- name: "Set fact: type of environment"
  set_fact:
    is_dev: "{{ archivematica_src_environment_type == 'development' }}"
    is_prod: "{{ archivematica_src_environment_type == 'production' }}"
  tags: "always" # inocuous to use always here

- name: "Set fact: environment vars"
  set_fact:
    archivematica_src_am_dashboard_environment:
      DJANGO_SETTINGS_MODULE: "{{ 'settings.local' if is_dev else 'settings.common' }}"
  tags: "always" # inocuous to use always here

- include: "tear-up.yml"
  tags: # do not use "always" tag in role, to avoid issues when including other roles in a playbook
  - "amsrc-ss"
  - "amsrc-pipeline"
  - "amsrc-devtools"
  - "amsrc-automationtools"
  - "amsrc-appraisaltab"


#
# archivematica-storage-service
#

- include: "ss-main.yml"
  tags:
   - "amsrc-ss"
  when: "archivematica_src_install_ss|bool"

- include: "ss-websrv-uwsgi.yml"
  tags:
   - "amsrc-ss"
  when: "archivematica_src_install_ss|bool and not(archivematica_src_ss_gunicorn|bool)"

- include: "ss-websrv-gunicorn.yml"
  tags:
   - "amsrc-ss"
  when: "archivematica_src_install_ss|bool and archivematica_src_ss_gunicorn|bool"


#
# archivematica pipeline install
#    (dashboard, MCP server, client)
#
#   0- Clone source repo
#   1- OS dependencies (debian packages)
#   2- python dependencies (pip packages)
#   3- OS configuration (user/directory/file creation/permissions/ownership)
#   4- Code install
#   5- Database config
#   6- web server config

- include: "pipeline-clonecode.yml"
  tags:
    - "amsrc-pipeline"
    - "amsrc-pipeline-clonecode"
  when: "archivematica_src_install_am|bool"

- include: "pipeline-deps.yml"
  tags:
    - "amsrc-pipeline"
    - "amsrc-pipeline-deps"
  when: "archivematica_src_install_am|bool"

- include: "pipeline-osconf.yml"
  tags:
    - "amsrc-pipeline"
    - "amsrc-pipeline-osconf"
  when: "archivematica_src_install_am|bool"

- include: "pipeline-instcode.yml"
  tags:
    - "amsrc-pipeline"
    - "amsrc-pipeline-instcode"
  when: "archivematica_src_install_am|bool"

- include: "pipeline-dbconf.yml"
  tags:
    - "amsrc-pipeline"
    - "amsrc-pipeline-dbconf"
  when: "archivematica_src_install_am|bool"

- include: "pipeline-websrv-modwsgi.yml"
  tags:
   - "amsrc-pipeline"
   - "amsrc-pipeline-websrv"
  when: "archivematica_src_install_am|bool and not(archivematica_src_am_dashboard_gunicorn|bool)"

- include: "pipeline-websrv-gunicorn.yml"
  tags:
   - "amsrc-pipeline"
   - "amsrc-pipeline-websrv"
  when: "archivematica_src_install_am|bool and archivematica_src_am_dashboard_gunicorn|bool"




#
# archivematica-devtools
#

- include: "am-devtools.yml"
  tags:
    - "amsrc-devtools"
  when: "archivematica_src_install_devtools|bool"

#
# automation-tools
#

- include: "automation-tools.yml"
  tags:
    - "amsrc-automationtools"
  when: "archivematica_src_install_automationtools|bool"

#
# appraisal-tab
#

- include: "appraisal-tab.yml"
  tags:
    - "amsrc-appraisaltab"
  when: "archivematica_src_install_appraisaltab|bool"
