---

#
#
# REMINDER: This role must be executed with sudo. We are going to be explicit
# when we DO NOT WANT to use sudo.
#
#

#
# Tear up
#

- include: "tear-up.yml"
  tags:
    - "always"

#
# archivematica-storage-service
#

- include: "archivematica-storage-service.yml"
  tags:
   - "amsrc-am-ss"

#
# archivematica-common
#

- include: "archivematica-common.yml"
  tags:
    - "amsrc-am-dashboard"
    - "amsrc-am-mcp-server"
    - "amsrc-am-mcp-client"

#
# archivematica-mcp-server
#

- include: "archivematica-mcp-server.yml"
  tags:
    - "amsrc-am-mcp-server"

#
# archivematica-mcp-client
#

- include: "archivematica-mcp-client.yml"
  tags:
    - "amsrc-am-mcp-client"

#
# archivematica-dashboard
#

- include: "archivematica-dashboard.yml"
  tags:
    - "amsrc-am-dashboard"