---

#
# Common tasks
#


- include: "tear-up.yml"
  tags:
# do not use "always" tag in role, to avoid issues when incuding other roles in a playbook
  - "amsrc-ss"
  - "amsrc-pipeline"
  - "amsrc-devtools"
  - "amsrc-automationtools"
  - "amsrc-appraisaltab"

#
# archivematica-storage-service
#

- include: "archivematica-storage-service.yml"
  tags:
   - "amsrc-ss"
  when: archivematica_src_install_ss == "yes"

#
# archivematica pipeline install
#    (dashboard, MCP server, client)
#
#   0- Clone source repo
#   1- OS dependencies (debian packages)
#   2- python dependencies (pip packages)
#   3- OS configuration (user/directory/file creation/permissions/ownership )
#   4- Code install
#   5- Database config
#   6- web server config

- include: "pipeline-clonecode.yml"
  tags:
    - "amsrc-pipeline"
    - "amsrc-pipeline-clonecode"
  when: archivematica_src_install_am == "yes"

- include: "pipeline-deps.yml"
  tags:
    - "amsrc-pipeline"
    - "amsrc-pipeline-deps"
  when: archivematica_src_install_am == "yes"

- include: "pipeline-osconf.yml"
  tags:
    - "amsrc-pipeline"
    - "amsrc-pipeline-osconf"
  when: archivematica_src_install_am == "yes"

- include: "pipeline-instcode.yml"
  tags:
    - "amsrc-pipeline"
    - "amsrc-pipeline-instcode"
  when: archivematica_src_install_am == "yes"

- include: "pipeline-dbconf.yml"
  tags:
    - "amsrc-pipeline"
    - "amsrc-pipeline-dbconf"
  when: archivematica_src_install_am == "yes"

- include: "pipeline-websrv.yml"
  tags:
    - "amsrc-pipeline"
    - "amsrc-pipeline-websrv"
  when: archivematica_src_install_am == "yes"

#
# archivematica-devtools
#

- include: "am-devtools.yml"
  tags:
    - "amsrc-devtools"
  when: archivematica_src_install_devtools == "yes"

#
# automation-tools
#

- include: "automation-tools.yml"
  tags:
    - "amsrc-automationtools"
  when: archivematica_src_install_automationtools == "yes"



#
# appraisal-tab
#

- include: "appraisal-tab.yml"
  tags:
    - "amsrc-appraisaltab"
  when: archivematica_src_install_appraisaltab == "yes"
