---

#
#
# REMINDERS:
#
# - This role needs root privileges but it is preferred to run it as a
#   regular user that can sudo.
# - At the moment, archivematica-mcp-server.yml will not be able to start the
#   service archivematica-mcp-server until the dashboard is installed later
#   via archivematica-dashboard.yml due to internal dependency issues. Our
#   temporary hack is to restart archivematica-mcp-server from
#   archivematica-dashboard.yml.
#
#

#
# Tear up
#

- include: "tear-up.yml"
  tags:
    - "always"

#
# archivematica-storage-service
#

- include: "archivematica-storage-service.yml"
  tags:
   - "amsrc-am-ss"

#
# archivematica-common
#

- include: "archivematica-common.yml"
  tags:
    - "amsrc-am-dashboard"
    - "amsrc-am-mcp-server"
    - "amsrc-am-mcp-client"

#
# archivematica-mcp-server
#

- include: "archivematica-mcp-server.yml"
  tags:
    - "amsrc-am-mcp-server"

#
# archivematica-mcp-client
#

- include: "archivematica-mcp-client.yml"
  tags:
    - "amsrc-am-mcp-client"

#
# archivematica-dashboard
#

- include: "archivematica-dashboard.yml"
  tags:
    - "amsrc-am-mcp-server"
    - "amsrc-am-dashboard"
