---
# tasks file for ansible-role-archivematica-src

- name: run the equivalent of apt-get update
  apt: update_cache=yes
  tags: 
    - amsrc-am-common
    - amsrc-am-dashboard
    - amsrc-am-mcp-server
    - amsrc-am-mcp-client
    - amsrc-am-ss

  
- name: Install python-curl
  sudo: yes
  apt: pkg='python-pycurl' state=latest
  tags: 
    - amsrc-am-common
    - amsrc-am-dashboard
    - amsrc-am-mcp-server
    - amsrc-am-mcp-client
    - amsrc-am-ss

- name: Add required PPAs
  sudo: yes
  apt_repository: repo=ppa:'{{ item }}' state=present
  with_items:
    - '{{ ppa }}'
  tags:
    - amsrc-am-common
    - amsrc-am-dashboard
    - amsrc-am-mcp-server
    - amsrc-am-mcp-client
    - amsrc-am-ss

- name: Add Universe repository
  sudo: yes
  apt_repository: repo='{{ item }}' state=present
  with_items:
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted universe multiverse"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security main restricted universe"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted universe multiverse"
  tags:
    - amsrc-am-common
    - amsrc-am-mcp-client

  

#########################################################
### Get the source (from a specified branch etc) 

- name: install git
  sudo: yes
  apt: pkg='git' state=latest update_cache=yes
  tags: 
    - amsrc-am-common
    - amsrc-am-dashboard
    - amsrc-am-mcp-server
    - amsrc-am-mcp-client
    - amsrc-am-ss


## for archivematica.git

  
- name: checkout archivematica code
  sudo: yes
  git: repo=https://github.com/artefactual/archivematica.git
       dest=/srv/archivematica 
       version={{ amdev_version }} 
  tags: 
    - amsrc-am-common
    - amsrc-am-dashboard
    - amsrc-am-mcp-server
    - amsrc-am-mcp-client



- name: git submodule init
  command: chdir=/srv/archivematica git submodule init
  tags: 
    - amsrc-am-common
    - amsrc-am-dashboard
    - amsrc-am-mcp-server
    - amsrc-am-mcp-client
  
- name: git submodule update
  command: chdir=/srv/archivematica git submodule update
  tags: 
    - amsrc-am-common
    - amsrc-am-dashboard
    - amsrc-am-mcp-server
    - amsrc-am-mcp-client

  
- name: get archivematica latest commit hash
  command: chdir=/srv/archivematica git rev-parse HEAD
  register: latest_commit
  tags: 
    - amsrc-am-common
    - amsrc-am-dashboard
    - amsrc-am-mcp-server
    - amsrc-am-mcp-client

- name: save archivematica last commit hash
  sudo: yes
  shell: echo {{ latest_commit.stdout }} > /srv/archivematica-commit.txt


## for archivematica-storage-service.git


- name: checkout archivematica-storage-service code
  sudo: yes
  git: repo=https://github.com/artefactual/archivematica-storage-service.git
       dest=/srv/archivematica-storage-service 
       version={{ ssdev_version }} 
  tags: 
    - amsrc-am-ss

- name: get archivematica-storage-service latest commit hash
  command: chdir=/srv/archivematica-storage-service git rev-parse HEAD
  register: latest_commit_ss
  tags: 
    - amsrc-am-ss


- name: save archivematica-storage-service last commit hash
  sudo: yes
  shell: echo {{ latest_commit_ss.stdout }} > /srv/archivematica-storage-service-commit.txt


## TODO: only perform the installation steps below if version has changed 



#########################################################

### archivematica-storage-service


## Install package dependencies (ref. debian/control )

- name: Install archivematica-storage-service package dependencies
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - python-lxml
    - nginx
    - unar 
    - uwsgi
    - uwsgi-plugin-python
  tags: amsrc-am-ss

# this not in the package dependencies but also required (pip compiling libraries)

- name: Install archivematica-storage-service additional package dependencies
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - python-virtualenv
    - python-dev
    - libxml2-dev 
    - libxslt1-dev
    
# (create virtualenv and pip install ref. dh-virtualenv )
- name: create virtualenv for archivematica-storage-service
  sudo: yes
  pip: chdir=/srv/archivematica-storage-service
       requirements=requirements.txt 
       virtualenv=/usr/share/python/archivematica-storage-service
       extra_args='--find-links lib'
  tags: amsrc-am-ss

# dh-virtualenv also seems to copy the storage_service dir to the virtualenv above (?)
- name: copy storage_service folder to archivematica-storage-service virtualenv site-packages
  sudo: yes
  command: rsync -a /srv/archivematica-storage-service/storage_service 
                /usr/share/python/archivematica-storage-service/lib/python2.7/site-packages
  tags: amsrc-am-ss
 

## copy (link) source files (ref. debian/archivematica-storage-service.install )

- name: create subdirectories for archivematica-storage-service source files
  sudo: yes
  file: dest={{ item }} state=directory 
  with_items: 
    - /var/archivematica/storage-service
    - /usr/lib/archivematica
  tags: amsrc-am-ss


- name: copy archivematica-storage-service source files
  sudo: yes
  command: rsync -a /srv/archivematica-storage-service/{{ item.src }} 
                    {{ item.dest }} 
  with_items:
    - { src: 'install/storage.ini', dest: '/etc/uwsgi/apps-available/' } 
    - { src: 'install/storage', dest: '/etc/nginx/sites-available/' } 
    - { src: 'install/.storage-service', dest: '/var/archivematica/' } 
    - { src: 'install/make_key.py', dest: '/var/archivematica/storage-service/' } 
    - { src: 'lib', dest: '/var/archivematica/storage-service/' } 
    - { src: 'storage_service/static', dest: '/var/archivematica/storage-service/' }
    - { src: 'storage_service/templates', dest: '/var/archivematica/storage-service/' }
  tags: amsrc-am-ss


## (ref. debian/postinst)

- name: call the debian/postinst script for archivematica-storage-service
  sudo: yes
  command: chdir=/srv/archivematica-storage-service/debian/ executable=/bin/bash source postinst
  tags: amsrc-am-ss



## ref. configure-storage-service.yml (ansible role that installs from packages)
- name: remove nginx default
  sudo: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  tags: amsrc-am-ss

- name: setup nginx sites available
  sudo: yes
  command: ln -s /etc/nginx/sites-available/storage /etc/nginx/sites-enabled/storage creates=/etc/nginx/sites-enabled/storage
  tags: amsrc-am-ss

- name: setup uwsgi apps avaiable
  sudo: yes
  command: ln -s /etc/uwsgi/apps-available/storage.ini /etc/uwsgi/apps-enabled/storage.ini creates=/etc/uwsgi/apps-enabled/storage.ini
  tags: amsrc-am-ss

- name: restart nginx 
  sudo: yes
  service: name=nginx state=reloaded
  tags: amsrc-am-ss

- name: restart uwsgi
  sudo: yes
  service: name=uwsgi state=restarted
  tags: amsrc-am-ss



#########################################################

### archivematica-common

## copy (link) source files (ref. debian/archivematica-common.install )

- name: create subdirectories for archivematica-common source files
  sudo: yes
  file: dest={{ item }} state=directory 
  with_items: 
    - /usr/lib/archivematica
    - /etc/archivematica
    - /usr/share/archivematica/archivematicaCommon
  tags: amsrc-am-common


- name: copy archivematica-common source files
  sudo: yes
  command: rsync -a /srv/archivematica/{{ item.src }} 
                    {{ item.dest }} 
  with_items:
    - { src: 'src/archivematicaCommon/etc/', dest: '/etc/archivematica/archivematicaCommon/' } 
    - { src: 'src/archivematicaCommon/lib/', dest: '/usr/lib/archivematica/archivematicaCommon/' }
    - { src: 'src/archivematicaCommon/requirements.txt', dest: '/usr/share/archivematica/archivematicaCommon/' }
    - { src: 'src/archivematicaCommon/requirements', dest: '/usr/share/archivematica/archivematicaCommon/' }
  tags: amsrc-am-common



## Install package dependencies (ref. debian/control )

- name: Install archivematica-common package dependencies
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - python
    - python-pip
    - python2.7-elementtree
    - python-mimeparse
    - python-dateutil
  tags: amsrc-am-common

## (ref. debian/postinst )

- name: Install archivematica-common pip dependencies
  sudo: yes
  pip: requirements=/srv/archivematica/src/archivematicaCommon/requirements.txt
  tags: amsrc-am-common


#########################################################

### archivematica-mcp-server


## copy (link) source files (ref. debian/archivematica-mcp-server.install )

- name: create subdirectories for archivematica-mcp-server source files
  sudo: yes
  file: dest={{ item }} state=directory 
  with_items: 
    - /etc/archivematica
    - /usr/lib/archivematica
    - /usr/share/archivematica
    - /usr/share/dbconfig-common/data/archivematica-mcp-server/install/
    - /usr/share/dbconfig-common/data/archivematica-mcp-server/upgrade/mysql/
  tags: amsrc-am-mcp-server



- name: copy archivematica-mcp-server source files
  sudo: yes
  command: rsync -a /srv/archivematica/{{ item.src }} 
                    {{ item.dest }} 
  with_items:
    - { src: 'src/MCPServer/etc/', dest: '/etc/archivematica/MCPServer/' } 
    - { src: 'src/MCPServer/lib/', dest: '/usr/lib/archivematica/MCPServer/' }
    - { src: 'src/MCPServer/share/', dest: '/usr/share/archivematica/MCPServer/' }
    - { src: 'src/MCPServer/share/mysql', dest: '/usr/share/dbconfig-common/data/archivematica-mcp-server/install/' }
    - { src: 'src/MCPServer/share/1.1.0', dest: '/usr/share/dbconfig-common/data/archivematica-mcp-server/upgrade/mysql/' }
    - { src: 'src/MCPServer/share/1.2.0', dest: '/usr/share/dbconfig-common/data/archivematica-mcp-server/upgrade/mysql/' }
    - { src: 'src/MCPServer/init/archivematica-mcp-server.conf', dest: '/etc/init/' }
  tags: amsrc-am-mcp-server
# NOTE: /src/MCPServer/share location is not as in the debian install scripts


## Install package dependencies (ref. debian/control )

- name: Install archivematica-mcp-server package dependencies
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - dbconfig-common
    - logapp
    - mysql-server
    - python-pyinotify
    - python-gearman
    - python-mysqldb
    - python-lxml
    - gearman
    - uuid
  tags: amsrc-am-mcp-server


# (ref. debian/config)

- name: Create mysql database for MCP 
  mysql_db: name=MCP state=present encoding=utf8 collation=utf8_unicode_ci
  register: createdb_result
  tags: amsrc-am-mcp-server

- name: initialize database MCP 
  mysql_db: name=MCP 
            state=import 
            target=/srv/archivematica/src/MCPServer/share/mysql
  when: createdb_result|changed

- name: create mysql user 
  mysql_user: name=archivematica 
              password=demo
              priv=MCP.*:ALL 
              state=present
  tags: amsrc-am-mcp-server


## (ref. debian/postinst )

- name: create /var/archivematica/sharedDirectory
  sudo: yes
  file: dest=/var/archivematica/sharedDirectory state=directory 

- name: create /var/archivematica/sharedDirectory structure
  sudo: yes
  command: rsync -a /usr/share/archivematica/MCPServer/sharedDirectoryStructure/ /var/archivematica/sharedDirectory/
# TODO: note that the location of sharedDirectory structure differs from the debian installer location
  


- name: add archivematica user to audio group
  user: name=archivematica groups=audio
 
- name: set owner, group of /var/archivematica recursively
  sudo: yes
  file: dest=/var/archivematica state=directory recurse=yes owner=archivematica group=archivematica 

- name: set owner, group of /var/archivematica/sharedDirectory recursively
  sudo: yes
  file: dest=/var/archivematica/sharedDirectory state=directory recurse=yes owner=archivematica group=archivematica 

  
- name: set permissions for /var/archivematica  
  sudo: yes
  command: chmod -R g+s "/var/archivematica/"
  
- name: set permissions for /var/archivematica/sharedDirectory
  sudo: yes
  command: chmod -R 664 "/var/archivematica/sharedDirectory" 

- name: set more permissions for /var/archivematica  
  sudo: yes
  shell: find -L /var/archivematica/ -type d  | sudo xargs -IF chmod u+rwx,g+rwxt,o-rwx F


- name: create user archivematica
  sudo: yes
  user: name=archivematica uid=333 group=archivematica system=yes home=/var/lib/archivematica/
  tags: amsrc-am-mcp-client



- name: add archivematica user permissions in visudo file
  lineinfile: dest=/etc/sudoers 
              state=present 
              regexp='^archivematica ALL\=' 
              line='archivematica ALL=NOPASSWD:/bin/mv,/bin/chown,/bin/chmod,/usr/bin/find,/usr/bin/gs,/usr/bin/inkscape' 
              validate='/usr/sbin/visudo -cf %s'


#########################################################
#########################################################

### archivematica-mcp-client


## copy (link) source files (ref. debian/archivematica-mcp-client.install )

- name: create subdirectories for archivematica-mcp-client source files
  sudo: yes
  file: dest={{ item }} state=directory 
  with_items: 
    - /etc/archivematica
    - /usr/lib/archivematica
  tags: amsrc-am-mcp-client



- name: copy(symlink) archivematica-mcp-client source files
  sudo: yes
  command: rsync -a /srv/archivematica/{{ item.src }} 
                    {{ item.dest }} 
  with_items:
    - { src: 'src/MCPClient/etc/', dest: '/etc/archivematica/MCPClient' }   
    - { src: 'src/MCPClient/lib/', dest: '/usr/lib/archivematica/MCPClient' }     
    - { src: 'src/MCPClient/init/archivematica-mcp-client.conf', dest: '/etc/init/' }
  tags: amsrc-am-mcp-client



## Install package dependencies (ref. debian/control )

- name: Install archivematica-mcp-client package dependencies
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - atool
    - bagit
    - bulk-extractor
    - clamav
    - clamav-daemon
    - ffmpeg 
    - fits
    - gearman
    - imagemagick
    - inkscape
    - jhove
    - libimage-exiftool-perl
    - libxml2-utils
    - logapp
    - md5deep
    - mediainfo
    - nfs-common
    - openjdk-7-jre-headless
    - p7zip-full
    - pbzip2
    - postfix
    - python-fido
    - python-gearman
    - python-lxml
    - python-mysqldb
    - python-pyicu
    - python-rfc6266
    - python-unidecode
    - readpst
    - rsync
    - sleuthkit
    - tesseract-ocr
    - tika
    - tree
    - ufraw
    - unrar-free
    - uuid  
  tags: amsrc-am-mcp-client




## (ref. debian/postinst )

- name: create user archivematica
  sudo: yes
  user: name=archivematica uid=333 group=archivematica system=yes home=/var/lib/archivematica/
  tags: amsrc-am-mcp-client




#########################################################



#########################################################

### archivematica-dashboard


## copy (link) source files (ref. debian/archivematica-common.install )

- name: create subdirectories for archivematica-dashboard source files
  sudo: yes
  file: dest={{ item }} state=directory 
  with_items: 
    - /usr/share/archivematica/archivematicaCommon
  tags: amsrc-am-dashboard


- name: copy archivematica-dashboard source files
  sudo: yes
  command: rsync -a /srv/archivematica/{{ item.src }} 
                    {{ item.dest }} 
  with_items:
    - { src: 'src/dashboard/src/', dest: '/usr/share/archivematica/dashboard/' }
  tags: amsrc-am-dashboard



## Install package dependencies (ref. debian/control )

- name: Install archivematica-dashboard package dependencies
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2-mpm-prefork
    - libapache2-mod-wsgi
    - python-pip
    - python-gearman
    - python-simplejson
  tags: amsrc-am-dashboard



## (ref. debian/postinst )

- name: Install archivematica-dashboard pip dependencies
  sudo: yes
  pip: requirements=/usr/share/archivematica/dashboard/requirements.txt
  tags: amsrc-am-dashboard

- name: enable mod-wsgi in apache
  sudo: yes
  command: a2enmod wsgi
  notify: restart apache2
  tags: amsrc-am-dashboard

- name: set MCP database charset
  command: mysql -u archivematica -pdemo MCP -e 'alter database MCP CHARACTER SET utf8 COLLATE utf8_unicode_ci'
  tags: amsrc-am-dashboard

- name: django syncdb
  command: /usr/share/archivematica/dashboard/manage.py syncdb --settings='settings.common'
  tags: amsrc-am-dashboard
  
- name: create archivematicaDashboard.log
  file: name=/tmp/archivematicaDashboard.log mode=666 state=touch
  tags: amsrc-am-dashboard

- name: create user archivematicadashboard
  sudo: yes
  user: name=archivematicadashboard uid=334 system=yes home=/var/lib/archivematica-django/
  tags: amsrc-am-dashboard





#########################################################


- name: copy apache config file  
  copy: src=apache.default dest=/etc/apache2/sites-available/default  owner=root group=root mode=644
  sudo: yes
  notify: restart apache2

- name: enable apache sites
  command: a2ensite default
  args:
    creates: /etc/apache2/sites-enabled/default
  sudo: yes
  notify: restart apache2



# (ref. role: archivematica configure-archivematica.yml)


- name: Get archivematica-dashboard configuration
  sudo: yes
  command: /usr/bin/wget -q https://raw.githubusercontent.com/artefactual/archivematica/stable/1.2.x/localDevSetup/apache/apache.default -O /etc/apache2/sites-available/default
- name: restart apache2
  sudo: yes
  service: name=apache2 state=reloaded
- name: run freshclam
  sudo: yes
  command: freshclam
- name: restart clamav
  sudo: yes
  service: name=clamav-daemon state=started
- name: restart elasticsearch
  sudo: yes
  service: name=elasticsearch state=restarted
- name: restart gearman
  sudo: yes
  service: name=gearman-job-server state=reloaded
- name: start mcp-server
  sudo: yes
  service: name=archivematica-mcp-server state=started
- name: start mcp-client
  sudo: yes
  service: name=archivematica-mcp-client state=started

 
- name: create user artefactual
  sudo: yes
  user: name=artefactual 
 
- name: checkout out Archivematica sample data
  sudo: yes
  git: repo=https://github.com/artefactual/archivematica-sampledata.git dest=/home/artefactual/archivematica-sampledata update=no

