---
# this task is needed to avoid problems when upgrading python package
- name: "virtualenv | Remove old virtualenv default dirs"
  file:
    state: absent
    path: "/usr/share/python/{{ item }}/"
  with_items:
    - "archivematica-dashboard"
    - "archivematica-mcp-client"
    - "archivematica-mcp-server"

- name: "virtualenv | Create environment and install requirements"
  pip:
    name:
      - "pip=={{ archivematica_src_pip_version }}"
      - "pip-tools=={{ archivematica_src_piptools_version }}"
      - "setuptools=={{ archivematica_src_setuptools_version }}"
      - "wheel=={{ archivematica_src_wheel_version }}"
    virtualenv: "{{ archivematica_src_am_virtualenv }}"
    state: "present"

- name: "virtualenv | Synchronize requirements"
  command: "{{ archivematica_src_am_virtualenv }}/bin/pip-sync {{ 'requirements-dev.txt' if is_dev else 'requirements.txt' }}"
  args:
    chdir: "{{ archivematica_src_dir }}/archivematica"
