---

- name: "fake administration 0001_initial"
  django_manage:
    command: "migrate --fake administration 0001_initial"
    app_path: "{{ archivematica_src_am_dashboard_app }}"
    pythonpath: "{{ archivematica_src_am_common_app }}"
    virtualenv: "{{ archivematica_src_am_dashboard_virtualenv }}"

- name: "fake main 0001_initial"
  django_manage:
    command: "migrate --fake main 0001_initial"
    app_path: "{{ archivematica_src_am_dashboard_app }}"
    pythonpath: "{{ archivematica_src_am_common_app }}"
    virtualenv: "{{ archivematica_src_am_dashboard_virtualenv }}"

- name: "fake main 0002_initial_data"
  django_manage:
    command: "migrate --fake main 0002_initial_data"
    app_path: "{{ archivematica_src_am_dashboard_app }}"
    pythonpath: "{{ archivematica_src_am_common_app }}"
    virtualenv: "{{ archivematica_src_am_dashboard_virtualenv }}"

- name: "fake fpr 0001_initial"
  django_manage:
    command: "migrate --fake fpr 0001_initial"
    app_path: "{{ archivematica_src_am_dashboard_app }}"
    pythonpath: "{{ archivematica_src_am_common_app }}"
    virtualenv: "{{ archivematica_src_am_dashboard_virtualenv }}"

- name: "fake fpr 0002_initial_data"
  django_manage:
    command: "migrate --fake fpr 0002_initial_data"
    app_path: "{{ archivematica_src_am_dashboard_app }}"
    pythonpath: "{{ archivematica_src_am_common_app }}"
    virtualenv: "{{ archivematica_src_am_dashboard_virtualenv }}"

- name: "Run manage.py migrate to apply remaining migrations on all apps"
  django_manage:
    command: "migrate"
    app_path: "{{ archivematica_src_am_dashboard_app }}"
    pythonpath: "{{ archivematica_src_am_common_app }}"
    virtualenv: "{{ archivematica_src_am_dashboard_virtualenv }}"
