---

###########################################################
#   4- Code install
###########################################################

- name: "symlink archivematica-common source files"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
  with_items:
    - src: "{{ archivematica_src_dir }}/archivematica/src/archivematicaCommon/lib"
      dest: "/usr/lib/archivematica/archivematicaCommon"
    - src: "{{ archivematica_src_dir }}/archivematica/src/archivematicaCommon/requirements.txt"
      dest: "/usr/share/archivematica/archivematicaCommon/requirements.txt"
    - src: "{{ archivematica_src_dir }}/archivematica/src/archivematicaCommon/requirements"
      dest: "/usr/share/archivematica/archivematicaCommon/requirements"

- name: "template archivematica-common /etc config"
  template:
    src: "etc_archivematica_archivematicaCommon_dbsettings.j2"
    dest: "/etc/archivematica/archivematicaCommon/dbsettings"

- name: "Copy archivematica-dashboard source files"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
  with_items:
    - src: "{{ archivematica_src_dir }}/archivematica/src/dashboard/src"
      dest: "/usr/share/archivematica/dashboard"


- name: "Copy archivematica-mcp-server source files"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
  with_items:
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/lib"
      dest: "/usr/lib/archivematica/MCPServer"
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/share"
      dest: "/usr/share/archivematica/MCPServer"
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/share/mysql"
      dest: "/usr/share/dbconfig-common/data/archivematica-mcp-server/install/mysql"
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/init/archivematica-mcp-server.conf"
      dest: "/etc/init/archivematica-mcp-server.conf"

- name: "template MCPServer /etc config"
  template:
    src: "etc_archivematica_MCPServer_serverConfig.conf.j2"
    dest: "/etc/archivematica/MCPServer/serverConfig.conf"


- name: "Copy archivematica-mcp-client source files"
  file: src={{ item.src }} dest={{ item.dest }} state=link
  with_items:
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPClient/etc"
      dest: "/etc/archivematica/MCPClient"
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPClient/lib/"
      dest: "/usr/lib/archivematica/MCPClient"
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPClient/init/archivematica-mcp-client.conf"
      dest: "/etc/init/archivematica-mcp-client.conf"



- name: "Copy archivematica-mcp-server init service"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
  with_items:
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/init/archivematica-mcp-server.conf"
      dest: "/etc/init/archivematica-mcp-server.conf"


- name: "Copy archivematica-mcp-client init service"
  file: src={{ item.src }} dest={{ item.dest }} state=link
  with_items:
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPClient/init/archivematica-mcp-client.conf"
      dest: "/etc/init/archivematica-mcp-client.conf"

- name: "Reload Upstart configuration"
  command: "initctl reload-configuration"
