---

- name: "fake administration 0001_initial"
  django_manage:
    command: "migrate --fake administration 0001_initial"
    app_path: "/usr/share/archivematica/dashboard/"
    settings: "settings.common"
    pythonpath: "/usr/lib/archivematica/archivematicaCommon"

- name: "fake main 0001_initial"
  django_manage:
    command: "migrate --fake main 0001_initial"
    app_path: "/usr/share/archivematica/dashboard/"
    settings: "settings.common"
    pythonpath: "/usr/lib/archivematica/archivematicaCommon"

- name: "fake main 0002_initial_data"
  django_manage:
    command: "migrate --fake main 0002_initial_data"
    app_path: "/usr/share/archivematica/dashboard/"
    settings: "settings.common"
    pythonpath: "/usr/lib/archivematica/archivematicaCommon"

- name: "fake fpr 0001_initial"
  django_manage:
    command: "migrate --fake fpr 0001_initial"
    app_path: "/usr/share/archivematica/dashboard/"
    settings: "settings.common"
    pythonpath: "/usr/lib/archivematica/archivematicaCommon"

- name: "fake fpr 0002_initial_data"
  django_manage:
    command: "migrate --fake fpr 0002_initial_data"
    app_path: "/usr/share/archivematica/dashboard/"
    settings: "settings.common"
    pythonpath: "/usr/lib/archivematica/archivematicaCommon"

- name: "Run manage.py migrate to apply remaining migrations on all apps"
  django_manage:
    command: "migrate"
    app_path: "/usr/share/archivematica/dashboard/"
    settings: "settings.common"
    pythonpath: "/usr/lib/archivematica/archivematicaCommon"
