---

###########################################################
#   5- Database reset (when flag enabled)
###########################################################

- name: "Drop MCP database"
  mysql_db:
    name: "MCP"
    state: "absent"
  when: "archivematica_src_reset_mcpdb|bool or archivematica_src_reset_am_all|bool"

###########################################################
#   5- Database config
###########################################################

# Note that when we are using mysql_db and mysql_user we are assuming that the
# root user has a local ~/.my.cnf configuration file with the credentials in it
# for the MySQL user.

- name: "Create MySQL database"
  mysql_db:
    name: "MCP"
    state: "present"
    encoding: "utf8"
    collation: "utf8_unicode_ci"
  when: 'archivematica_src_am_database_host == "localhost"'

# TODO: need to change the mysql password for user archivematica

- name: "Create MySQL user"
  mysql_user:
    name: "archivematica"
    password: "demo"
    priv: "MCP.*:ALL"
    state: "present"
  when: 'archivematica_src_am_database_host == "localhost"'

- include: "pipeline-dbconf-migrate-1_4-to-1_5.yml"
  when: "archivematica_src_am_migrate_from_v1_4|bool"

- name: "Run migrations"
  django_manage:
    command: "migrate"
    app_path: "/usr/share/archivematica/dashboard/"
    settings: "settings.production"
    pythonpath: "/usr/lib/archivematica/archivematicaCommon"
    virtualenv: "/usr/share/python/archivematica-dashboard"
  environment: "{{ archivematica_src_am_dashboard_environment }}"
  tags: "amsrc-pipeline-dbconf-syncdb"
