---

###########################################################
#   4- Code install
###########################################################

- name: "Symlink source files"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
  with_items:
    
    # archivematicaCommon
    - src: "{{ archivematica_src_dir }}/archivematica/src/archivematicaCommon/lib"
      dest: "/usr/lib/archivematica/archivematicaCommon"
    - src: "{{ archivematica_src_dir }}/archivematica/src/archivematicaCommon/requirements.txt"
      dest: "/usr/share/archivematica/archivematicaCommon/requirements.txt"
    - src: "{{ archivematica_src_dir }}/archivematica/src/archivematicaCommon/requirements"
      dest: "/usr/share/archivematica/archivematicaCommon/requirements"

    # Dashboard
    - src: "{{ archivematica_src_dir }}/archivematica/src/dashboard/src"
      dest: "/usr/share/archivematica/dashboard"

    # MCPServer
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/lib"
      dest: "/usr/lib/archivematica/MCPServer"

    # MCPClient
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPClient/lib/"
      dest: "/usr/lib/archivematica/MCPClient"

- name: "set_fact: set python locations for MCP server and client"
  set_fact:
    mcp_server_python_path: "/usr/share/python/archivematica-mcp-server/bin/python"
    mcp_client_python_path: "/usr/share/python/archivematica-mcp-client/bin/python"

#
# upstart
#

- name: "upstart | Install services"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: "yes"
  when:
    - "ansible_service_mgr == 'upstart'"
  with_items:
    - src: "etc/init/archivematica-mcp-server.conf"
      dest: "/etc/init/archivematica-mcp-server.conf"
    - src: "etc/init/archivematica-mcp-client.conf"
      dest: "/etc/init/archivematica-mcp-client.conf"

- name: "Reload Upstart configuration"
  command: "initctl reload-configuration"
  when: 
    - "ansible_service_mgr == 'upstart'"

#
# systemd
#

- name: "systemd | Install configuration files"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: "yes"
  when:
    - "ansible_service_mgr == 'systemd'"
  with_items:
    - src: "etc/systemd/system/archivematica-mcp-server.service.j2"
      dest: "/etc/systemd/system/archivematica-mcp-server.service"
    - src: "etc/systemd/system/archivematica-mcp-client.service.j2"
      dest: "/etc/systemd/system/archivematica-mcp-client.service"
    - src: "etc/sysconfig/archivematica-mcp-server.j2"
      dest: "{{ systemd_environment_path}}/archivematica-mcp-server"
    - src: "etc/sysconfig/archivematica-mcp-client.j2"
      dest: "{{ systemd_environment_path}}/archivematica-mcp-client"

- name: "Reload systemd config"
  command: "systemctl daemon-reload"
  tags: "amsrc-ss-websrv"
  when:
    - "ansible_service_mgr == 'systemd'"
