---

###########################################################
#   0- Clone source repo
###########################################################

- name: "Delete pychache, pyc and pyo files/dir"
  command: "{{ item }}"
  args:
    removes: "{{ archivematica_src_dir }}/archivematica"
  loop:
    - 'find {{ archivematica_src_dir }}/archivematica -type f -name "*.py[co]" -delete'
    - 'find {{ archivematica_src_dir }}/archivematica -type d -name "__pycache__" -delete'

- name: "Get git config global safe directories dir"
  shell: "git config --global --get-all safe.directory || echo ''"
  register: "__git_config_global_safe_dir"
  become_flags: "-E"

- name: "Set AM source directory as git safe dir"
  command: "git config --global --add safe.directory {{ archivematica_src_dir }}/archivematica"
  become_flags: "-E"
  when:
    - archivematica_src_dir + '/archivematica' not in __git_config_global_safe_dir.stdout_lines

- name: "Checkout Archivematica code"
  git:
    repo: "{{ archivematica_src_am_repo }}"
    dest: "{{ archivematica_src_dir }}/archivematica"
    version: "{{ archivematica_src_am_version }}"
    force: "yes"
    accept_hostkey: "yes"
    recursive: "no"
  become_flags: "-E"

- name: "Download AM1.12 osdeps files for Xenial"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  loop:
    - { url: "https://raw.githubusercontent.com/artefactual/archivematica/stable/1.12.x/src/MCPClient/osdeps/Ubuntu-16.json", dest: "{{ archivematica_src_dir }}/archivematica/src/MCPClient/osdeps/Ubuntu-16.json" }
    - { url: "https://raw.githubusercontent.com/artefactual/archivematica/stable/1.12.x/src/MCPServer/osdeps/Ubuntu-16.json", dest: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/osdeps/Ubuntu-16.json" }
    - { url: "https://raw.githubusercontent.com/artefactual/archivematica/stable/1.12.x/src/dashboard/osdeps/Ubuntu-16.json", dest: "{{ archivematica_src_dir }}/archivematica/src/dashboard/osdeps/Ubuntu-16.json" }
  when:
    - ansible_distribution_version is version('16.04', '==')
