---
###########################################################
#   6- web server config
###########################################################


- name: "Enable mod-wsgi in Apache"
  command: "a2enmod wsgi"
  notify:
    - "Restart Apache"

- name: "Remove default Apache server sites"
  command: "a2dissite {{ item }}"
  with_items:
    - "000-default"
    - "default"
  notify:
    - "Restart Apache"

- name: "Template dashboard apache2 config"
  template:
    src: "etc_apache2_sites_dashboard.conf.j2"
    dest: "/etc/apache2/sites-available/dashboard.conf"

- name: "Enable apache dashboard site"
  command: "a2ensite dashboard"
  args:
    creates: "/etc/apache2/sites-enabled/dashboard.conf"
  notify:
    - "Restart Apache"

- name: "Enable services"
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: "yes"
  with_items:
    - "elasticsearch"
    - "archivematica-mcp-server"
    - "archivematica-mcp-client"
    - "apache2"
