---
###########################################################
#   6- web server config
###########################################################


- name: "Enable mod-wsgi in Apache"
  command: "a2enmod wsgi"
  notify:
    - "Restart Apache"


- name: "Remove default Apache server"
  command: "a2dissite 000-default"
  notify:
    - "Restart Apache"

- name: "Copy Apache config file"
  copy:
    src: "apache.default"
    dest: "/etc/apache2/sites-available/default.conf"
  notify:
    - "Restart Apache"

- name: "Enable Apache site"
  command: "a2ensite default"
  args:
    creates: "/etc/apache2/sites-enabled/default.conf"
  notify:
    - "Restart Apache"

- name: "Get archivematica-dashboard configuration"
  get_url:
    url: "https://raw.githubusercontent.com/artefactual/archivematica/stable/1.2.x/localDevSetup/apache/apache.default"
    dest: "/etc/apache2/sites-available/default"

- name: "Enable services"
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: "yes"
  with_items:
    - "elasticsearch"
    - "archivematica-mcp-server"
    - "archivematica-mcp-client"
    - "apache2"
