---

###########################################################
#   6- dashboard web server config - when using gunicorn with nginx
###########################################################

# Note: the playbook assumes the use of /etc/nginx/{sites-available|sites-enabled}
#       directories for site config files, even on CentOS/RedHat

- name: "Template dashboard nginx sites-available config file"
  template:
    src: "etc_nginx_sites_dashboard-gunicorn.conf.j2"
    dest: "/etc/nginx/sites-available/dashboard.conf"
    backup: "yes"

- name: "Template gunicorn configuration file"
  template:
    src: "etc_archivematica_dashboard.gunicorn-config.py.j2"
    dest: "/etc/archivematica/dashboard.gunicorn-config.py"
    backup: "yes"

- name: "set_fact: set gunicorn path to correct value"
  set_fact:
    dashboard_gunicorn_path: "/usr/share/python/archivematica-dashboard/bin/gunicorn"

- name: "Config dashboard gunicorn upstart (/etc/init)"
  template:
    src: "etc_init_archivematica-dashboard.conf.j2"
    dest: "/etc/init/archivematica-dashboard.conf"
    backup: "yes"
  when: 
     - ansible_service_mgr == "upstart"

- name: "Reload Upstart configuration"
  command: "initctl reload-configuration"
  when:
    - ansible_service_mgr == "upstart"

- name: "Add dashboard gunicorn systemd (/etc/systemd)"
  template:
    src: "etc/systemd/system/archivematica-dashboard.service.j2"
    dest: "/etc/systemd/system/archivematica-dashboard.service"
    backup: "yes"
  when:
    - ansible_service_mgr == "systemd"

- name: "Reload systemd config"
  command: "systemctl daemon-reload"
  when:
    - ansible_service_mgr == "systemd"

- name: "Remove Nginx default server"
  file:
    path: "{{ item }}"
    state: "absent"
  with_items:
    - "/etc/nginx/sites-available/default"
    - "/etc/nginx/sites-available/default.conf"

- name: "Set up Nginx server"
  file:
    src: "/etc/nginx/sites-available/dashboard.conf"
    dest: "/etc/nginx/sites-enabled/dashboard.conf"
    state: "link"

# SSL configuration tasks - begin
- name: "Template nginx ssl config file"
  template:
    src: "etc_nginx_sites_dashboard-ssl-gunicorn.conf.j2"
    dest: "/etc/nginx/sites-available/dashboard-ssl.conf"
    backup: "yes"
  when: "archivematica_src_ssl|bool"

- name: "Remove non-ssl config from sites-enabled"
  file:
    path: "/etc/nginx/sites-enabled/dashboard.conf"
    state: "absent"
  when: "archivematica_src_ssl|bool"

- name: "Add ssl config to sites-enabled"
  file:
    src: "/etc/nginx/sites-available/dashboard-ssl.conf"
    dest: "/etc/nginx/sites-enabled/dashboard-ssl.conf"
    state: "link"
  when: "archivematica_src_ssl|bool"
# SSL configuration tasks - end

- name: "Enable services"
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: "yes"
  with_items:
    - "archivematica-mcp-server"
    - "archivematica-mcp-client"
    - "archivematica-dashboard"
    - "nginx"
  when:
    - ansible_service_mgr == "upstart"

- name: "Enable services"
  systemd:
    name: "{{ item }}"
    state: "restarted"
    enabled: "yes"
    daemon_reload: "yes"
  with_items:
    - "archivematica-mcp-server"
    - "archivematica-mcp-client"
    - "archivematica-dashboard"
    - "nginx"
  when:
    - ansible_service_mgr == "systemd"

