---
# Archivematica Storage Service installer

###########################################################
#   0- Clone source repo
###########################################################

- name: "Checkout archivematica-storage-service code"
  git:
    repo: "{{ archivematica_src_ss_repo }}"
    dest: "{{ archivematica_src_dir }}/archivematica-storage-service"
    version: "{{ archivematica_src_ss_version }}"
    force: "yes"
    accept_hostkey: "yes"
  tags: "amsrc-ss-clone"

# For some reason, some dirs in the cloned source code
# are not sometimes readable by all. Add a task to fix it
# For some other reason this task does not always work
# blame ansible  :-/
# Update: this problem may have been fixed with postinst removal
- name: "Ensure the source code is readable by all"
  file:
    path: "{{ archivematica_src_dir }}/archivematica-storage-service"
    mode: "o+rX"
    recurse: "yes"
  become: "yes"
  tags: "amsrc-ss-clone"


###########################################################
#   1- OS package dependencies
###########################################################

- name: "include ss-osdeps.yml"
  include: "ss-osdeps.yml"
  tags: "amsrc-ss-osdeps"
  static: no


###########################################################
#   2- Python dependencies (pip packages)
###########################################################

# We need to install pip before.
- name: "Create virtualenv for archivematica-storage-service"
  pip:
    name: "pip"
    chdir: "{{ archivematica_src_dir }}/archivematica-storage-service"
    virtualenv: "/usr/share/python/archivematica-storage-service"
    state: "latest"
  tags: "amsrc-ss-pydep"

- name: "Create virtualenv for archivematica-storage-service, pip install requirements"
  pip:
    chdir: "{{ archivematica_src_dir }}/archivematica-storage-service"
    requirements: "{{ 'requirements/test.txt' if is_dev else 'requirements.txt'}}"
    virtualenv: "/usr/share/python/archivematica-storage-service"
    state: "latest"
  tags: "amsrc-ss-pydep"


###########################################################
#   3- OS configuration (user/directory/file creation/permissions/ownership )
###########################################################

- name: "Create subdirectory for archivematica-storage-service source files"
  file:
    dest: "{{ item }}"
    state: "directory"
  with_items:
    - "/usr/lib/archivematica"
  tags: "amsrc-ss-osconf"

- name: "Create subdirectory for archivematica-storage-service database file"
  file:
    dest: "{{ item }}"
    state: "directory"
    owner: "archivematica"
    group: "archivematica"
  with_items:
    - "/var/archivematica/storage-service"
  tags: "amsrc-ss-osconf"

- name: "Create subdirectories for archivematica-storage-service config"
  file:
    dest: "{{ item }}"
    state: "directory"
  with_items:
    - "/etc/archivematica"
  tags: "amsrc-ss-osconf"


###########################################################
#   4- SS code install
###########################################################

# storage service base dir:  /usr/lib/archivematica/storage-service

- name: "Copy archivematica-storage-service source files"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
  with_items:
    - src: "{{ archivematica_src_dir }}/archivematica-storage-service/storage_service"
      dest: "/usr/lib/archivematica/storage-service"
  tags: "amsrc-ss-code"

- name: "Run SS django collectstatic"
  django_manage:
    command: "collectstatic"
    app_path: "/usr/lib/archivematica/storage-service"
    virtualenv: "/usr/share/python/archivematica-storage-service"
  environment: "{{ archivematica_src_ss_environment }}"
  tags: ["amsrc-ss-code", "amsrc-ss-code-collectstatic"]
