###########################################################
#   6- web server config - when using gunicorn with nginx
###########################################################

- name: "set nginx sites-available config file"
  template:
    src: "etc_nginx_sites_storage-gunicorn.conf.j2"
    dest: "/etc/nginx/sites-available/storage.conf"
    backup: "yes"
  tags: "amsrc-ss-websrv"

- name: "set gunicorn init file"
  template:
    src: "etc_init_archivematica-storage-service.conf.j2"
    dest: "/etc/init/archivematica-storage-service.conf"
    backup: "yes"
  tags: "amsrc-ss-websrv"

- name: "Reload Upstart configuration"
  command: "initctl reload-configuration"
  tags: "amsrc-ss-websrv"

- name: "Remove Nginx default server"
  file:
    path: "{{ item }}"
    state: "absent"
  with_items:
    - "/etc/nginx/sites-available/default"
    - "/etc/nginx/sites-available/default.conf"
    - "/etc/nginx/sites-enabled/default"
    - "/etc/nginx/sites-enabled/default.conf"
  tags: "amsrc-ss-websrv"

- name: "Set up Nginx server"
  file:
    src: "/etc/nginx/sites-available/storage.conf"
    dest: "/etc/nginx/sites-enabled/storage.conf"
    state: "link"
  tags: "amsrc-ss-websrv"

- name: "Enable services"
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: "yes"
  with_items:
    - "archivematica-storage-service"
    - "nginx"
  tags: "amsrc-ss-websrv"
