###########################################################
#   6- web server config - when using gunicorn with nginx
###########################################################

# Note: the playbook assumes the use of /etc/nginx/{sites-available|sites-enabled}
#       directories for site config files, even on CentOS/RedHat

- name: "set nginx sites-available config file"
  template:
    src: "etc_nginx_sites_storage-gunicorn.conf.j2"
    dest: "/etc/nginx/sites-available/storage.conf"
    backup: "yes"
  tags: "amsrc-ss-websrv"

- name: "Template gunicorn configuration file"
  template:
    src: "etc_archivematica_storage-service.gunicorn-config.py.j2"
    dest: "/etc/archivematica/storage-service.gunicorn-config.py"
    backup: "yes"
  tags: "amsrc-ss-websrv"


- name: "Config storage service gunicorn upstart (/etc/init)"
  template:
    src: "etc_init_archivematica-storage-service.conf.j2"
    dest: "/etc/init/archivematica-storage-service.conf"
    backup: "yes"
  tags: "amsrc-ss-websrv"
  when: 
    - ansible_service_mgr == "upstart"

- name: "Reload Upstart configuration"
  command: "initctl reload-configuration"
  tags: "amsrc-ss-websrv"
  when: 
    - ansible_service_mgr == "upstart"


- name: "Add storage service gunicorn systemd (/etc/systemd)"
  template:
    src: "etc/systemd/system/archivematica-storage-service.service.j2"
    dest: "/etc/systemd/system/archivematica-storage-service.service"
    backup: "yes"
  tags: "amsrc-ss-websrv"
  when: 
    - ansible_service_mgr == "systemd"

- name: "Add storage service gunicorn systemd env file (in {{ systemd_environment_path }})"
  template:
    src: "etc/sysconfig/archivematica-storage-service.j2"
    dest: "{{ systemd_environment_path }}/archivematica-storage-service"
    backup: "yes"
  tags: "amsrc-ss-websrv"
  when: 
    - ansible_service_mgr == "systemd"

- name: "Disable Nginx default server config"
  file:
    path: "{{ item }}"
    state: "absent"
  with_items:
    - "/etc/nginx/sites-enabled/default"
    - "/etc/nginx/sites-enabled/default.conf"
  tags: "amsrc-ss-websrv"

- name: "Set up Nginx server"
  file:
    src: "/etc/nginx/sites-available/storage.conf"
    dest: "/etc/nginx/sites-enabled/storage.conf"
    state: "link"
  tags: "amsrc-ss-websrv"

# SSL configuration tasks - begin
- name: "Template nginx sites-available ssl config file"
  template:
    src: "etc_nginx_sites_storage-ssl-gunicorn.conf.j2"
    dest: "/etc/nginx/sites-available/storage-ssl.conf"
    backup: "yes"
  when: "archivematica_src_ssl|bool"
  tags: "amsrc-ss-websrv"

- name: "Remove non-ssl config from sites-enabled"
  file:
    path: "/etc/nginx/sites-enabled/storage.conf"
    state: "absent"
  when: "archivematica_src_ssl|bool"
  tags: "amsrc-ss-websrv"

- name: "Add ssl config to sites-enabled"
  file:
    src: "/etc/nginx/sites-available/storage-ssl.conf"
    dest: "/etc/nginx/sites-enabled/storage-ssl.conf"
    state: "link"
  when: "archivematica_src_ssl|bool"
  tags: "amsrc-ss-websrv"
# SSL configuration tasks - end

- name: "Enable services (upstart)"
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: "yes"
  with_items:
    - "archivematica-storage-service"
    - "nginx"
  when:
    - ansible_service_mgr == "upstart"
  tags: "amsrc-ss-websrv"

- name: "Enable services (systemd)"
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: "yes"
    daemon_reload: "yes"
  with_items:
    - "archivematica-storage-service"
    - "nginx"
  when:
    - ansible_service_mgr == "systemd"
  tags: "amsrc-ss-websrv"

