---

- name: "Run the equivalent of apt-get update"
  apt:
    update_cache: "yes"

- name: "remove broken python-pip (for ubuntu 14.04)"
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - "python-pip"
    
- name: "Install necessary prerequisite packages"
  apt:
    pkg: "{{ item }}"
    state: "latest"
  with_items:
    - "python-pycurl"
    - "git"
    - "python-setuptools"
    - "python-virtualenv"

- name: "install pip with easy_install"
  easy_install:
    name: pip
    state: latest

# apt repository config for external dependencies 
#   - if ppa: add the repo
#   - if not ppa: add the key and the repo
- name: "Check if externals repo is a ppa"
  set_fact:
    extrepo_is_ppa: "{{ 'ppa:' in archivematica_src_externals_repo }}"

- name: "Add external dependencies PPA repository"
  apt_repository:
    repo: "{{ archivematica_src_externals_repo }}"
    state: "present"
  when: "extrepo_is_ppa|bool"

- name: "Add external dependencies repository key"
  apt_key:
    id: "{{ archivematica_src_externals_repo_key_id }}"
    url: "{{ archivematica_src_externals_repo_key_url }}"
    state: "present"
    validate_certs: "no"
  when: "not(extrepo_is_ppa|bool)"

- name: "Add external dependencies repository"
  apt_repository:
    repo: "deb [arch=amd64] {{ archivematica_src_externals_repo }} {{ ansible_distribution_release }} main"
    state: "present"
  when: "not(extrepo_is_ppa|bool)"


- name: "Create user archivematica"
  user:
    name: "archivematica"
    uid: "333"
    system: "yes"
    groups: "audio"
    home: "/var/lib/archivematica"

- name: "Add archivematica user permissions in visudo file"
  lineinfile:
    dest: "/etc/sudoers"
    state: "present"
    regexp: "^archivematica ALL\\="
    line: "archivematica ALL=NOPASSWD:/bin/mv,/bin/chown,/bin/chmod,/usr/bin/find,/usr/bin/gs,/usr/bin/inkscape"
    validate: "/usr/sbin/visudo -cf %s"

- name: "Expand archivematica_src_dir"
  set_fact:
    archivematica_src_dir: "{{ archivematica_src_dir|expanduser }}"

- name: "Create archivematica_src_dir"
  file:
    state: "directory"
    path: "{{ archivematica_src_dir }}"

- name: "Checkout out archivematica-sampledata repository"
  git:
    repo: "https://github.com/artefactual/archivematica-sampledata.git"
    dest: "~/archivematica-sampledata"
    update: "no"
  when: "archivematica_src_install_sample_data|bool"
  become: "no"
